python3: can't open file 'generator_prompt_V2.py': [Errno 2] No such file or directory
